### ISSUE TITLE
Convert to typescript based action

### ISSUE THREAD

**Issue by rajbos** [devops-actions/load-used-actions#13]
# Convert to TypeScript-based action

## Overview
Rewrite the current PowerShell/Docker-based action as a TypeScript/Node.js action. This eliminates the Docker container startup overhead and aligns with the GitHub Actions ecosystem standard.

### Current (PowerShell)
```
entrypoint.ps1 → load-used-actions.ps1 → github-calls.ps1
```
- Docker container action (`runs.using: docker`)
- `powershell-yaml` for YAML parsing
- Manual REST API calls with Basic Auth + pagination

### Target (TypeScript)
```
src/main.ts → src/actions-scanner.ts → src/github-client.ts
```
- Node.js action (`runs.using: node20`)
- `js-yaml` for YAML parsing
- `@octokit/rest` for GitHub API (built-in pagination, auth, rate limiting)
- `@actions/core` for inputs/outputs/logging

### Phase 0: External validation test harness (FIRST)
Create an integration test that runs BOTH the PowerShell and TypeScript versions against the same org and compares outputs. This ensures behavioral parity before we swap.

- [ ] Create `tests/integration/parity-test.ts` that:
  - Calls the TypeScript implementation against a known org
  - Compares output JSON structure against a known-good baseline
  - Validates: action count, action names, container images, composite action detection
- [ ] Baseline from the current PowerShell action output

### Phase 1: Project scaffolding
- [ ] Initialize Node.js project (`package.json`, `tsconfig.json`)
- [ ] Add dependencies: `@actions/core`, `@actions/github`, `@octokit/rest`, `js-yaml`
- [ ] Add dev dependencies: `typescript`, `vitest`, `@types/js-yaml`
- [ ] Configure `action.yml` to use `runs.using: node20` with `dist/index.js`
- [ ] Set up `ncc` bundling for single-file distribution

### Phase 2: Core modules
Map PowerShell functions 1:1 to TypeScript:

**`src/github-client.ts`** (replaces `github-calls.ps1`)
- [ ] `getOctokit(pat)` — Create authenticated Octokit instance
- [ ] `findAllRepos(org, includeArchived)` — List repos with pagination (org + user fallback)
- [ ] `getAllFilesInPath(repo, path)` — List files in a directory
- [ ] `getFileInfo(repo, path)` — Get single file metadata
- [ ] `getRawFile(url)` — Download raw file content

**`src/actions-scanner.ts`** (replaces `load-used-actions.ps1`)
- [ ] `getActionsFromWorkflow(yaml, fileName, repo)` — Parse workflow YAML, extract actions + containers
- [ ] `getActionsFromCompositeAction(yaml, fileName, repo)` — Parse composite action YAML
- [ ] `getAllUsedActionsFromRepo(repo)` — Scan workflows + composite actions for a repo
- [ ] `summarizeActionsUsed(actions)` — Aggregate by actionLink + type, count usage
- [ ] `loadAllActions(org, includeArchived)` — Main orchestration

**`src/main.ts`** (replaces `entrypoint.ps1`)
- [ ] Read inputs via `@actions/core`
- [ ] Call `loadAllActions()`
- [ ] Write output files + set action outputs

### Phase 3: Internal unit tests
- [ ] `tests/unit/actions-scanner.test.ts`
  - Test `getActionsFromWorkflow` with all existing YAML fixtures
  - Test `getActionsFromCompositeAction` with composite-action.yml
  - Test `summarizeActionsUsed` aggregation logic
  - Test container image detection (docker://, job containers, services)
  - Test reusable workflow detection
- [ ] `tests/unit/github-client.test.ts`
  - Test `findAllRepos` with mocked Octokit (org, user fallback, archived filter)
  - Test pagination handling
  - Test error handling (rate limits, 404s)
- [ ] `tests/unit/main.test.ts`
  - Test input validation
  - Test output file writing

### Phase 4: Integration + CI
- [ ] Update `.github/workflows/testing.yml` to run TypeScript tests
- [ ] Keep PowerShell tests temporarily for parity validation
- [ ] Run parity test against a real org

### Phase 5: Cleanup
- [ ] Remove `Src/PowerShell/` directory
- [ ] Remove `Dockerfile`
- [ ] Update `action.yml` to `runs.using: node20`
- [ ] Update README with any changes
- [ ] Remove PowerShell test files

## Key type definitions

```typescript
interface ActionReference {
  actionLink: string;
  actionRef: string | null;
  actionVersionComment: string | null;
  workflowFileName: string;
  repo: string;
  type: 'action' | 'reusable workflow' | 'container-image';
}

interface SummarizedAction {
  type: string;
  actionLink: string;
  count: number;
  workflows: WorkflowReference[];
}

interface WorkflowReference {
  repo: string;
  workflowFileName: string;
  actionRef: string | null;
  actionVersionComment: string | null;
}
```

## Dependencies

| Package | Purpose | Replaces |
|---------|---------|----------|
| `@actions/core` | Inputs, outputs, logging | PowerShell env vars |
| `@actions/github` | GitHub context | `$env:GITHUB_*` |
| `@octokit/rest` | REST API with pagination | `CallWebRequest` |
| `js-yaml` | YAML parsing | `powershell-yaml` |
| `@vercel/ncc` | Bundle to single file | Docker COPY |
| `vitest` | Unit + integration tests | Pester |

## Output compatibility
The JSON output format must remain identical to preserve backward compatibility for downstream consumers.

**Comment by sebastienvermeille** [comment]
Hi @rajbos do you mean you would like to have this action ported to Typescript rather than PowerShell?

Interesting move, I think it will ease contributions

**Comment by rajbos** [comment]
Correct. I have a customer that does not have any PowerShell anywhere, and is running their containers exclusively from an internal Artifactory cache. I've learned that them embracing this action has an extra hurdle, as they need to overwrite the container being used and then pull in that extra dependency into Artifactory (so another bump on the road). 

Just making this a Typescript based action makes all of those bumps go away, and thus makes it easier to run. It does add a dependency on the correct Node version on the runner, which I am OK with. as I keep those up to date as much as possible in my actions anyway (and most self-hosted runners have to follow along anyway, as GitHub deprecates the old version anyway every once in a while).

Seems like I already started a conversion in the [typescript](https://github.com/devops-actions/load-used-actions/tree/typescript) branch, although it misses your last updates ofc. Not sure how far along I was already though.
